language: python
python :
  - "3.8"
  - "3.7"
  - "3.6"
install: pip install tox-travis codecov
script :
  tox -- --cov --cov-append

services:
  - mysql
  - redis-server

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

before_script:
  - psql -U postgres -c "create extension postgis; create database travis_ci_test;"
  - mysql -e 'create database travis_ci_test character set utf8 collate utf8_general_ci;'

after_success:
  - codecov
